### ISSUE TITLE
libPluginProtocol cannot build for android on OSX

### ISSUE THREAD

**Issue by yalab** [cocos2d-x/plugin-x#98]
I cannot build libPluginProtocol on develop branch.
I tried that 'tools/toolsForPublish/publishPlugin.sh' ant plugin-publish task add -v option and run tools/publish.sh then I got such back trace

```
     [echo] Resolving Build Target for libPluginProtocol...

BUILD FAILED
/opt/android-sdk/tools/ant/build.xml:542: Unable to resolve project target 'android-7'
    at com.android.ant.GetTargetTask.execute(GetTargetTask.java:162)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.Main.runBuild(Main.java:851)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

Total time: 0 seconds
cp: /Users/yalab/project/oke-ya/zeron/cocos2d/plugin/protocols/proj.android/bin/*.jar: No such file or directory
```

Thanks.

**Comment by yalab** [comment]
Its my fail. I have to install 'Build Toool' from android sdk manager.
sorry.
